baseURL = "https://blog.deet.dog/"
disqusShortname = ""
languageCode = "en-us"
paginate = "5"
summaryLength = "10"
theme = "northernlab-hugo"
title = "Deet's blog"
[[menu.footer]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "about"
name = "Deet"
weight = 1
[[menu.main]]
URL = "author/mirkka-and-ozz"
name = "Authors"
weight = 2
[outputs]
home = ["HTML", "AMP", "RSS", "JSON"]
[params]
author = "Juan Antonio Osorio Robles"
contact_form_action = "#"
copyright = "&copy; 2020 Ozz &amp; Mirkka All Rights Reserved"
description = "Diary of raising a rescue dog."
google_analitycs_id = "UA-124742268-2"
google_tag_manager = ""
home = "Home"
logo = "images/logo.png"
[params.banner]
bgImage = "images/banner/Deeetsyyy.png"
image = ""
title = "Hi! I'm Deet! I'm a rescue dog from Romania living a new life in Finland. Welcome to my journey in this new country with my new family."
[params.cta]
description = "Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus."
enable = false
image = "images/hugo-muscot.svg"
title = "Get the best hugo templates"
[params.cta.button]
enable = false
label = "Visit Here"
link = "https://gethugothemes.com/shop/"
[[params.plugins.css]]
link = "css/custom.css"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[params.preloader]
enable = true
preloader = ""
[params.search]
enable = true
